
version: '3.8'

services:
  hfxt-web:
    image: hfxt-web:latest
    ports:
      - "9003:8080"
    volumes:
      - ./hop-data/lic:/etc/lic
      - ./hop-data/config:/usr/local/tomcat/webapps/ROOT/config
      - ./hop-data/audit:/usr/local/tomcat/webapps/ROOT/audit
    restart: unless-stopped